#!/bin/bash

DESTINATION="net.connman"
DBUS_PATH="/org/sailfishos/connman/mdm/iptables"
METHOD_PREFIX="org.sailfishos.connman.mdm.iptables"

# Send dbus message with dbus-send, input: $1=Methodname $2=last parameter
# $3=expected result $4-> = Whole content
function send_message()
{
	LAST_PARAM=""
	
	if [ ! -z "$2" ] ; then
		case "$2" in
			"ADD")
				LAST_PARAM="uint16:0"
				;;
			"REMOVE")
				LAST_PARAM="uint16:1"
				;;
			"FLUSH")
				LAST_PARAM="uint16:2"
				;;
			"ACCEPT")
				LAST_PARAM="uint16:1"
				;;
			"DROP")
				LAST_PARAM="uint16:2"
				;;
			*)
				LAST_PARAM="string:$2"
				;;
		esac
	fi

	RETURN=$(dbus-send --system --type=method_call --print-reply --dest="$DESTINATION" "$DBUS_PATH" "$METHOD_PREFIX.$1" "${@:4}" $LAST_PARAM 2>&1)
	
	if [[ $RETURN && $(echo "$RETURN"|grep -e "uint16 $3") ]] ; then
		echo 0
	else
		echo "failure processing rule $METHOD_PREFIX.$1 ${@:4} $LAST_PARAM - method returned: $RETURN"
	fi
}

# 1:Method 2:ADD/REMOVE 3:result 4:...rule: table, chain, target, rest of rule
function send_rule_message()
{	
	RESULT=$(send_message "$1" "$2" "$METHOD_INPUTS_RESULT" "string:filter" "string:$3" "string:$4" ${@:5})
	
	if [[ "$RESULT" != "0" ]] ; then
		log "$RESULT"
		echo 1
	else
		echo 0
	fi
}
